#!/usr/bin/env ruby

keypad_map = { 1 => nil, 2 => %w(a b c), 3 => %w(d e f), 4 => %w(g h i), 5 => %w(j k l) }

number = ARGV[0]
numbers = number.chars

strings = ['']

numbers.each do |n|
  chars = keypad_map[n.to_i] || []

  strings.length.times do |i|
    prefix = strings.shift

    chars.each do |ch|
      strings << prefix + ch
    end
  end
end

puts strings.inspect
